<?php

/**
 * @file
 * Contains domain_redirect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function domain_redirect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the domain_redirect module.
    case 'help.page.domain_redirect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Redirects a group to your domain if configured.') . '</p>';
      return $output;

    default:
  }
}